import React from 'react';
import { useForm, Controller, FieldValues, FieldError } from 'react-hook-form';
import Select from 'react-select'; // Using react-select for auto-suggestions
import { Button } from '../ui/Button'; // Assuming you have your own Button component
import { Input } from '../ui/Input'; // Assuming you have your own Input component
import { Label } from '../ui/Label'; // Assuming you have your own Label component
import { createVehicle } from '../../../../database/vehicles/vehicles'; // Import the createVehicle API function

// List of states for suggestions
const stateOptions = [
  { value: 'Czechia', label: 'Czechia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'France', label: 'France' },
  { value: 'Italy', label: 'Italy' },
  // Add more states as needed
];

const vehicleTypeOptions = [
  { value: 'Car', label: 'Car' },
  { value: 'Truck', label: 'Truck' },
  { value: 'Motorcycle', label: 'Motorcycle' },
  { value: 'Armored', label: 'Armored' }
];

const fuelTypeOptions = [
  { value: 'Diesel', label: 'Diesel' },
  { value: 'Natural 95', label: 'Natural 95' },
  { value: 'Natural 98', label: 'Natural 98' },
  { value: 'Electric', label: 'Electric' },
  { value: 'Hybrid', label: 'Hybrid' },
  { value: 'Plug-in Hybrid', label: 'Plug-in Hybrid' },
  { value: 'CNG', label: 'CNG' },
  { value: 'LPG', label: 'LPG' },
  { value: 'Hydrogen', label: 'Hydrogen' },
  { value: 'Ethanol', label: 'Ethanol' },
  { value: 'Bio-Diesel', label: 'Bio-Diesel' },
  { value: 'Synthetic Fuels', label: 'Synthetic Fuels' }
];

interface AddVehicleModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (newVehicle: any) => void; // Add specific type for new vehicle
  loading: boolean;  // Add loading state to props
  error: string | null; // Add error state to props
}

const AddVehicleModal: React.FC<AddVehicleModalProps> = ({ isOpen, onClose, onSave }) => {
  const { control, handleSubmit, formState: { errors } } = useForm();

  const onSubmit = async (data: FieldValues) => {
    try {
      // Construct the new vehicle object
      const newVehicle = {
        vehicle_id: 0, // Vehicle ID will be generated by the server
        model_id: data.model?.value || 0, // Assuming model is a select field with value containing ID
        registration_number: data.registrationNumber,
        vin: data.vin,
        category_id: 1, // Set a default category or fetch it based on your context
        country_id: 1, // Set a default country or fetch it based on your context
        fuel_type: data.fuelType?.value, // Assuming fuelType is a select field with value containing the fuel type
        vehicle_status: 'Active', // Default status, adjust as needed
        created_at: new Date().toISOString(), // Server should handle date if needed
        company_id: 1, // Assuming company_id is 1, replace with dynamic value if necessary
      };

      // Assuming `company_id` is available in your context or props
      const company_id = 1; // Update this based on your context or how it's passed

      // Call the createVehicle API
      const createdVehicle = await createVehicle(company_id, newVehicle);

      // After the vehicle is successfully created, close the modal and reset the form
      onSave(createdVehicle); // Pass the created vehicle to the parent
      onClose(); // Close the modal
    } catch (error) {
      console.error('Error creating vehicle:', error);
      // Optionally, you could set an error state to display an error message
    }
  };

  if (!isOpen) return null;

  // Custom styles for the select dropdown to match the input fields
  const customSelectStyles = {
    control: (styles: any) => ({
      ...styles,
      borderRadius: '0.375rem', // Match border radius with the input field
      height: '2.5rem', // Match height with input field
      padding: '0 0.5rem', // Add horizontal padding
      border: '1px solid #e5e7eb', // Match input field border
      boxShadow: 'none', // Remove box shadow
      display: 'flex', // Flexbox layout to align content vertically
      alignItems: 'center', // Vertically center the content
      '&:hover': {
        borderColor: '#3b82f6', // Add a hover effect like the input field
      },
    }),
    menu: (styles: any) => ({
      ...styles,
      borderRadius: '0.375rem', // Match menu corners
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)', // Add subtle shadow for dropdown
      marginTop: 0, // Remove any margin at the top
    }),
    option: (styles: any, { isSelected }: { isSelected: boolean }) => ({
      ...styles,
      backgroundColor: isSelected ? '#3b82f6' : 'transparent', // Highlight selected option
      color: isSelected ? '#ffffff' : '#000000', // Text color for selected option
      display: 'flex', // Use flexbox to align the text
      alignItems: 'center', // Vertically center the text in each option
      padding: '0.5rem 1rem', // Add padding around the option
      '&:hover': {
        backgroundColor: '#d1d5db', // Highlight on hover
      },
    }),
  };

  return (
    <div className="modal-overlay">
      <div className="modal-content relative">
        <button
          onClick={onClose}
          className="absolute top-3 right-5 text-2xl font-bold text-gray-700 hover:text-gray-500"
        >
          &times; {/* This is the "X" symbol */}
        </button>

        <h2 className="text-2xl font-bold text-[#061f39] mb-4">Add New Vehicle</h2>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          {/* Vehicle Type */}
          <div>
            <Label htmlFor="vehicleType" required>
              Vehicle Type
            </Label>
            <Controller
              name="vehicleType"
              control={control}
              rules={{ required: 'Vehicle Type is required' }}
              render={({ field }) => (
                <div className="dropdown-container relative">
                  <Select {...field} id="vehicleType" options={vehicleTypeOptions} placeholder="Start typing to search..." styles={customSelectStyles} />
                </div>
              )}
            />
            {errors.vehicleType && (
              <p className="text-red-500 text-xs">{(errors.vehicleType as FieldError).message}</p>
            )}
          </div>

          {/* Brand and Model */}
          <div className="flex gap-4">
            <div className="flex-1">
              <Label htmlFor="brand" required>
                Brand
              </Label>
              <Controller
                name="brand"
                control={control}
                rules={{ required: 'Brand is required' }}
                render={({ field }) => <Input {...field} id="brand" placeholder="Enter brand (e.g., Ford)" />}
              />
              {errors.brand && (
                <p className="text-red-500 text-xs">{(errors.brand as FieldError).message}</p>
              )}
            </div>
            <div className="flex-1">
              <Label htmlFor="model" required>
                Model
              </Label>
              <Controller
                name="model"
                control={control}
                rules={{ required: 'Model is required' }}
                render={({ field }) => <Input {...field} id="model" placeholder="Enter model (e.g., F-150)" />}
              />
              {errors.model && (
                <p className="text-red-500 text-xs">{(errors.model as FieldError).message}</p>
              )}
            </div>
          </div>

          {/* Registration Row (State and Registration Number in the same row) */}
          <div className="flex gap-4">
            <div className="flex-1">
              <Label htmlFor="registrationState" required>
                Registration State
              </Label>
              <Controller
                name="registrationState"
                control={control}
                rules={{ required: 'Registration State is required' }}
                render={({ field }) => (
                  <Select
                    {...field}
                    options={stateOptions}
                    placeholder="Start typing to search..."
                    styles={customSelectStyles}
                  />
                )}
              />
              {errors.registrationState && (
                <p className="text-red-500 text-xs">{(errors.registrationState as FieldError).message}</p>
              )}
            </div>

            <div className="flex-1">
              <Label htmlFor="registrationNumber" required>
                Registration Number
              </Label>
              <Controller
                name="registrationNumber"
                control={control}
                rules={{ required: 'Registration Number is required' }}
                render={({ field }) => <Input {...field} id="registrationNumber" placeholder="ABC 1234" />}
              />
              {errors.registrationNumber && (
                <p className="text-red-500 text-xs">{(errors.registrationNumber as FieldError).message}</p>
              )}
            </div>
          </div>

          {/* VIN */}
          <div>
            <Label htmlFor="vin" required>
              VIN
            </Label>
            <Controller
              name="vin"
              control={control}
              rules={{ required: 'VIN is required' }}
              render={({ field }) => <Input {...field} id="vin" placeholder="Enter Vehicle Identification Number" />}
            />
            {errors.vin && (
              <p className="text-red-500 text-xs">{(errors.vin as FieldError).message}</p>
            )}
          </div>

          {/* Fuel Type */}
          <div>
            <Label htmlFor="fuelType" required>
              Fuel Type
            </Label>
            <Controller
              name="fuelType"
              control={control}
              rules={{ required: 'Fuel Type is required' }}
              render={({ field }) => (
                <div className="dropdown-container relative">
                  <Select {...field} id="fuelType" options={fuelTypeOptions} placeholder="Start typing to search..." styles={customSelectStyles} />
                </div>
              )}
            />
            {errors.fuelType && (
              <p className="text-red-500 text-xs">{(errors.fuelType as FieldError).message}</p>
            )}
          </div>

          {/* Submit Button */}
          <Button type="submit" className="bg-green-500 text-white mt-4 w-full">
            Add Vehicle
          </Button>
        </form>
      </div>
    </div>
  );
};

export default AddVehicleModal;
